/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiConversationsIdRouteImport } from './routes/api/conversations.$id'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'
import { Route as ApiConversationsIdMessagesRouteImport } from './routes/api/conversations.$id.messages'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api/auth/callback/google'
import { Route as ApiAuthCallbackDiscordRouteImport } from './routes/api/auth/callback/discord'

const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiConversationsIdRoute = ApiConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiConversationsRoute,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const ApiConversationsIdMessagesRoute =
  ApiConversationsIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiConversationsIdRoute,
  } as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackDiscordRoute = ApiAuthCallbackDiscordRouteImport.update({
  id: '/api/auth/callback/discord',
  path: '/api/auth/callback/discord',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/auth/callback/discord': typeof ApiAuthCallbackDiscordRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/auth/callback/discord': typeof ApiAuthCallbackDiscordRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/conversations/$id': typeof ApiConversationsIdRouteWithChildren
  '/api/auth/callback/discord': typeof ApiAuthCallbackDiscordRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/downloads'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/projects'
    | '/settings'
    | '/api/chat'
    | '/api/conversations'
    | '/chat/$id'
    | '/api/admin/users'
    | '/api/conversations/$id'
    | '/api/auth/callback/discord'
    | '/api/auth/callback/google'
    | '/api/conversations/$id/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/downloads'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/projects'
    | '/settings'
    | '/api/chat'
    | '/api/conversations'
    | '/chat/$id'
    | '/api/admin/users'
    | '/api/conversations/$id'
    | '/api/auth/callback/discord'
    | '/api/auth/callback/google'
    | '/api/conversations/$id/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/downloads'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/api/conversations'
    | '/_authenticated/chat/$id'
    | '/api/admin/users'
    | '/api/conversations/$id'
    | '/api/auth/callback/discord'
    | '/api/auth/callback/google'
    | '/api/conversations/$id/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DownloadsRoute: typeof DownloadsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthCallbackDiscordRoute: typeof ApiAuthCallbackDiscordRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/conversations/$id': {
      id: '/api/conversations/$id'
      path: '/$id'
      fullPath: '/api/conversations/$id'
      preLoaderRoute: typeof ApiConversationsIdRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/conversations/$id/messages': {
      id: '/api/conversations/$id/messages'
      path: '/messages'
      fullPath: '/api/conversations/$id/messages'
      preLoaderRoute: typeof ApiConversationsIdMessagesRouteImport
      parentRoute: typeof ApiConversationsIdRoute
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/discord': {
      id: '/api/auth/callback/discord'
      path: '/api/auth/callback/discord'
      fullPath: '/api/auth/callback/discord'
      preLoaderRoute: typeof ApiAuthCallbackDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiConversationsIdRouteChildren {
  ApiConversationsIdMessagesRoute: typeof ApiConversationsIdMessagesRoute
}

const ApiConversationsIdRouteChildren: ApiConversationsIdRouteChildren = {
  ApiConversationsIdMessagesRoute: ApiConversationsIdMessagesRoute,
}

const ApiConversationsIdRouteWithChildren =
  ApiConversationsIdRoute._addFileChildren(ApiConversationsIdRouteChildren)

interface ApiConversationsRouteChildren {
  ApiConversationsIdRoute: typeof ApiConversationsIdRouteWithChildren
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsIdRoute: ApiConversationsIdRouteWithChildren,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DownloadsRoute: DownloadsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthCallbackDiscordRoute: ApiAuthCallbackDiscordRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
